# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Only For Developers', max_length=20, null=True, unique=True)),
                ('title', models.TextField(blank=True, null=True, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufactory_created_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
